package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

/**
 * Roletofun generated by hbm2java
 */
public class Roletofun implements java.io.Serializable {

	private int roleId;
	private TFun TFun;
	private TRole TRole;

	public Roletofun() {
	}

	public Roletofun(TRole TRole) {
		this.TRole = TRole;
	}

	public Roletofun(TFun TFun, TRole TRole) {
		this.TFun = TFun;
		this.TRole = TRole;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public TFun getTFun() {
		return this.TFun;
	}

	public void setTFun(TFun TFun) {
		this.TFun = TFun;
	}

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

}
