package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TDepot generated by hbm2java
 */
public class TDepot implements java.io.Serializable {

	private int depotId;
	private TDepartment TDepartment;
	private String class_;
	private Set TFas = new HashSet(0);

	public TDepot() {
	}

	public TDepot(int depotId) {
		this.depotId = depotId;
	}

	public TDepot(int depotId, TDepartment TDepartment, String class_, Set TFas) {
		this.depotId = depotId;
		this.TDepartment = TDepartment;
		this.class_ = class_;
		this.TFas = TFas;
	}

	public int getDepotId() {
		return this.depotId;
	}

	public void setDepotId(int depotId) {
		this.depotId = depotId;
	}

	public TDepartment getTDepartment() {
		return this.TDepartment;
	}

	public void setTDepartment(TDepartment TDepartment) {
		this.TDepartment = TDepartment;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public Set getTFas() {
		return this.TFas;
	}

	public void setTFas(Set TFas) {
		this.TFas = TFas;
	}

}
