package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TDepartment generated by hbm2java
 */
public class TDepartment implements java.io.Serializable {

	private int departmentId;
	private String departmentName;
	private Set TFas = new HashSet(0);
	private Set TDepots = new HashSet(0);

	public TDepartment() {
	}

	public TDepartment(int departmentId) {
		this.departmentId = departmentId;
	}

	public TDepartment(int departmentId, String departmentName, Set TFas, Set TDepots) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.TFas = TFas;
		this.TDepots = TDepots;
	}

	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public Set getTFas() {
		return this.TFas;
	}

	public void setTFas(Set TFas) {
		this.TFas = TFas;
	}

	public Set getTDepots() {
		return this.TDepots;
	}

	public void setTDepots(Set TDepots) {
		this.TDepots = TDepots;
	}

}
