package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

/**
 * TDepot generated by hbm2java
 */
public class TDepot implements java.io.Serializable {

	private int depotId;
	private Integer department;
	private String class_;

	public TDepot() {
	}

	public TDepot(int depotId) {
		this.depotId = depotId;
	}

	public TDepot(int depotId, Integer department, String class_) {
		this.depotId = depotId;
		this.department = department;
		this.class_ = class_;
	}

	public int getDepotId() {
		return this.depotId;
	}

	public void setDepotId(int depotId) {
		this.depotId = depotId;
	}

	public Integer getDepartment() {
		return this.department;
	}

	public void setDepartment(Integer department) {
		this.department = department;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

}
