package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * TFa generated by hbm2java
 */
public class TFa implements java.io.Serializable {

	private int faid;
	private TDepartment TDepartment;
	private TDepot TDepot;
	private TFaclass TFaclass;
	private TFaunit TFaunit;
	private String faname;
	private Integer number;
	private String model;
	private String manufactor;
	private String dom;
	private String source;
	private String pic;
	private Integer userLife;
	private Date postingDate;
	private Double netSalvage;
	private Double univalent;
	private String ps;
	private String state;

	public TFa() {
	}

	public TFa(int faid) {
		this.faid = faid;
	}

	public TFa(int faid, TDepartment TDepartment, TDepot TDepot, TFaclass TFaclass, TFaunit TFaunit, String faname,
			Integer number, String model, String manufactor, String dom, String source, String pic, Integer userLife,
			Date postingDate, Double netSalvage, Double univalent, String ps, String state) {
		this.faid = faid;
		this.TDepartment = TDepartment;
		this.TDepot = TDepot;
		this.TFaclass = TFaclass;
		this.TFaunit = TFaunit;
		this.faname = faname;
		this.number = number;
		this.model = model;
		this.manufactor = manufactor;
		this.dom = dom;
		this.source = source;
		this.pic = pic;
		this.userLife = userLife;
		this.postingDate = postingDate;
		this.netSalvage = netSalvage;
		this.univalent = univalent;
		this.ps = ps;
		this.state = state;
	}

	public int getFaid() {
		return this.faid;
	}

	public void setFaid(int faid) {
		this.faid = faid;
	}

	public TDepartment getTDepartment() {
		return this.TDepartment;
	}

	public void setTDepartment(TDepartment TDepartment) {
		this.TDepartment = TDepartment;
	}

	public TDepot getTDepot() {
		return this.TDepot;
	}

	public void setTDepot(TDepot TDepot) {
		this.TDepot = TDepot;
	}

	public TFaclass getTFaclass() {
		return this.TFaclass;
	}

	public void setTFaclass(TFaclass TFaclass) {
		this.TFaclass = TFaclass;
	}

	public TFaunit getTFaunit() {
		return this.TFaunit;
	}

	public void setTFaunit(TFaunit TFaunit) {
		this.TFaunit = TFaunit;
	}

	public String getFaname() {
		return this.faname;
	}

	public void setFaname(String faname) {
		this.faname = faname;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getManufactor() {
		return this.manufactor;
	}

	public void setManufactor(String manufactor) {
		this.manufactor = manufactor;
	}

	public String getDom() {
		return this.dom;
	}

	public void setDom(String dom) {
		this.dom = dom;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public Integer getUserLife() {
		return this.userLife;
	}

	public void setUserLife(Integer userLife) {
		this.userLife = userLife;
	}

	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	public Double getNetSalvage() {
		return this.netSalvage;
	}

	public void setNetSalvage(Double netSalvage) {
		this.netSalvage = netSalvage;
	}

	public Double getUnivalent() {
		return this.univalent;
	}

	public void setUnivalent(Double univalent) {
		this.univalent = univalent;
	}

	public String getPs() {
		return this.ps;
	}

	public void setPs(String ps) {
		this.ps = ps;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
