package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TFaclass generated by hbm2java
 */
public class TFaclass implements java.io.Serializable {

	private int faclassId;
	private String faclassName;
	private Integer faclassParentId;
	private Set TFas = new HashSet(0);

	public TFaclass() {
	}

	public TFaclass(int faclassId) {
		this.faclassId = faclassId;
	}

	public TFaclass(int faclassId, String faclassName, Integer faclassParentId, Set TFas) {
		this.faclassId = faclassId;
		this.faclassName = faclassName;
		this.faclassParentId = faclassParentId;
		this.TFas = TFas;
	}

	public int getFaclassId() {
		return this.faclassId;
	}

	public void setFaclassId(int faclassId) {
		this.faclassId = faclassId;
	}

	public String getFaclassName() {
		return this.faclassName;
	}

	public void setFaclassName(String faclassName) {
		this.faclassName = faclassName;
	}

	public Integer getFaclassParentId() {
		return this.faclassParentId;
	}

	public void setFaclassParentId(Integer faclassParentId) {
		this.faclassParentId = faclassParentId;
	}

	public Set getTFas() {
		return this.TFas;
	}

	public void setTFas(Set TFas) {
		this.TFas = TFas;
	}

}
