package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

/**
 * TFaclass generated by hbm2java
 */
public class TFaclass implements java.io.Serializable {

	private int faclassId;
	private String faclassName;
	private Integer faclassParentId;

	public TFaclass() {
	}

	public TFaclass(int faclassId) {
		this.faclassId = faclassId;
	}

	public TFaclass(int faclassId, String faclassName, Integer faclassParentId) {
		this.faclassId = faclassId;
		this.faclassName = faclassName;
		this.faclassParentId = faclassParentId;
	}

	public int getFaclassId() {
		return this.faclassId;
	}

	public void setFaclassId(int faclassId) {
		this.faclassId = faclassId;
	}

	public String getFaclassName() {
		return this.faclassName;
	}

	public void setFaclassName(String faclassName) {
		this.faclassName = faclassName;
	}

	public Integer getFaclassParentId() {
		return this.faclassParentId;
	}

	public void setFaclassParentId(Integer faclassParentId) {
		this.faclassParentId = faclassParentId;
	}

}
