package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TFaunit generated by hbm2java
 */
public class TFaunit implements java.io.Serializable {

	private int faunitId;
	private String faunitName;
	private Set TFas = new HashSet(0);

	public TFaunit() {
	}

	public TFaunit(int faunitId) {
		this.faunitId = faunitId;
	}

	public TFaunit(int faunitId, String faunitName, Set TFas) {
		this.faunitId = faunitId;
		this.faunitName = faunitName;
		this.TFas = TFas;
	}

	public int getFaunitId() {
		return this.faunitId;
	}

	public void setFaunitId(int faunitId) {
		this.faunitId = faunitId;
	}

	public String getFaunitName() {
		return this.faunitName;
	}

	public void setFaunitName(String faunitName) {
		this.faunitName = faunitName;
	}

	public Set getTFas() {
		return this.TFas;
	}

	public void setTFas(Set TFas) {
		this.TFas = TFas;
	}

}
