package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

/**
 * TFaunit generated by hbm2java
 */
public class TFaunit implements java.io.Serializable {

	private int faunitId;
	private String faunitName;

	public TFaunit() {
	}

	public TFaunit(int faunitId) {
		this.faunitId = faunitId;
	}

	public TFaunit(int faunitId, String faunitName) {
		this.faunitId = faunitId;
		this.faunitName = faunitName;
	}

	public int getFaunitId() {
		return this.faunitId;
	}

	public void setFaunitId(int faunitId) {
		this.faunitId = faunitId;
	}

	public String getFaunitName() {
		return this.faunitName;
	}

	public void setFaunitName(String faunitName) {
		this.faunitName = faunitName;
	}

}
