package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TFun generated by hbm2java
 */
public class TFun implements java.io.Serializable {

	private int funId;
	private String funName;
	private String funUrl;
	private Set TRoles = new HashSet(0);

	public TFun() {
	}

	public TFun(int funId) {
		this.funId = funId;
	}

	public TFun(int funId, String funName, String funUrl, Set TRoles) {
		this.funId = funId;
		this.funName = funName;
		this.funUrl = funUrl;
		this.TRoles = TRoles;
	}

	public int getFunId() {
		return this.funId;
	}

	public void setFunId(int funId) {
		this.funId = funId;
	}

	public String getFunName() {
		return this.funName;
	}

	public void setFunName(String funName) {
		this.funName = funName;
	}

	public String getFunUrl() {
		return this.funUrl;
	}

	public void setFunUrl(String funUrl) {
		this.funUrl = funUrl;
	}

	public Set getTRoles() {
		return this.TRoles;
	}

	public void setTRoles(Set TRoles) {
		this.TRoles = TRoles;
	}

}
