package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

/**
 * TFunId generated by hbm2java
 */
public class TFunId implements java.io.Serializable {

	private Integer funId;
	private String funName;
	private String funUrl;

	public TFunId() {
	}

	public TFunId(Integer funId, String funName, String funUrl) {
		this.funId = funId;
		this.funName = funName;
		this.funUrl = funUrl;
	}

	public Integer getFunId() {
		return this.funId;
	}

	public void setFunId(Integer funId) {
		this.funId = funId;
	}

	public String getFunName() {
		return this.funName;
	}

	public void setFunName(String funName) {
		this.funName = funName;
	}

	public String getFunUrl() {
		return this.funUrl;
	}

	public void setFunUrl(String funUrl) {
		this.funUrl = funUrl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TFunId))
			return false;
		TFunId castOther = (TFunId) other;

		return ((this.getFunId() == castOther.getFunId()) || (this.getFunId() != null && castOther.getFunId() != null
				&& this.getFunId().equals(castOther.getFunId())))
				&& ((this.getFunName() == castOther.getFunName()) || (this.getFunName() != null
						&& castOther.getFunName() != null && this.getFunName().equals(castOther.getFunName())))
				&& ((this.getFunUrl() == castOther.getFunUrl()) || (this.getFunUrl() != null
						&& castOther.getFunUrl() != null && this.getFunUrl().equals(castOther.getFunUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFunId() == null ? 0 : this.getFunId().hashCode());
		result = 37 * result + (getFunName() == null ? 0 : this.getFunName().hashCode());
		result = 37 * result + (getFunUrl() == null ? 0 : this.getFunUrl().hashCode());
		return result;
	}

}
