package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private Roletofun roletofun;
	private Set usertoroles = new HashSet(0);

	public TRole() {
	}

	public TRole(int roleId) {
		this.roleId = roleId;
	}

	public TRole(int roleId, String roleName, Roletofun roletofun, Set usertoroles) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roletofun = roletofun;
		this.usertoroles = usertoroles;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Roletofun getRoletofun() {
		return this.roletofun;
	}

	public void setRoletofun(Roletofun roletofun) {
		this.roletofun = roletofun;
	}

	public Set getUsertoroles() {
		return this.usertoroles;
	}

	public void setUsertoroles(Set usertoroles) {
		this.usertoroles = usertoroles;
	}

}
