package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private Set TFuns = new HashSet(0);
	private Set TUsers = new HashSet(0);

	public TRole() {
	}

	public TRole(int roleId) {
		this.roleId = roleId;
	}

	public TRole(int roleId, String roleName, Set TFuns, Set TUsers) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.TFuns = TFuns;
		this.TUsers = TUsers;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getTFuns() {
		return this.TFuns;
	}

	public void setTFuns(Set TFuns) {
		this.TFuns = TFuns;
	}

	public Set getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set TUsers) {
		this.TUsers = TUsers;
	}

}
