package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int userId;
	private String userName;
	private String password;
	private Usertorole usertorole;

	public TUser() {
	}

	public TUser(int userId) {
		this.userId = userId;
	}

	public TUser(int userId, String userName, String password, Usertorole usertorole) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.usertorole = usertorole;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Usertorole getUsertorole() {
		return this.usertorole;
	}

	public void setUsertorole(Usertorole usertorole) {
		this.usertorole = usertorole;
	}

}
