package com.ywg.model;
// Generated 2017-2-26 13:23:03 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private int userId;
	private String userName;
	private String password;
	private Set TRoles = new HashSet(0);

	public TUser() {
	}

	public TUser(int userId) {
		this.userId = userId;
	}

	public TUser(int userId, String userName, String password, Set TRoles) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.TRoles = TRoles;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getTRoles() {
		return this.TRoles;
	}

	public void setTRoles(Set TRoles) {
		this.TRoles = TRoles;
	}

}
