package com.ywg.model;
// Generated 2017-2-25 19:54:26 by Hibernate Tools 5.2.0.CR1

/**
 * Usertorole generated by hbm2java
 */
public class Usertorole implements java.io.Serializable {

	private int userId;
	private TRole TRole;
	private TUser TUser;

	public Usertorole() {
	}

	public Usertorole(TUser TUser) {
		this.TUser = TUser;
	}

	public Usertorole(TRole TRole, TUser TUser) {
		this.TRole = TRole;
		this.TUser = TUser;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

}
